### PR TITLE
Use shutdown endpoint to restart butlerd. Fixes #2032

### LINKED ISSUE #2032: butlerd lifecycle improvements
When a computer goes to sleep, butlerd may close normally?

```
20:15:47.323 INFO (m/reac/updater) Scheduling next game update check for Fri Aug 03 2018 22:45:18 GMT+0200 (Romance Daylight Time)
(butlerd) no handler for notification Log
(butlerd) no handler for notification Log
(butlerd) no handler for notification Log
Uncaught network error: Error: net::ERR_ABORTED
Uncaught network error: Error: net::ERR_ABORTED

VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV

20:22:29.366 INFO (m/reac/setup) butlerd instance 1 has closed.

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

07:27:41.583 INFO (m/reac/updater) Regularly scheduled check for game updates...
07:27:41.598 INFO (m/reac/updater) Scheduling next game update check for Sat Aug 04 2018 09:53:34 GMT+0200 (Romance Daylight Time)
[7008:0804/092742.268:WARNING:dns_config_service_win.cc(669)] Failed to read DnsConfig.
07:27:42.749 INFO (broth :: butler:windows-amd64-head) Using local, so, not upgrading.
07:27:44.762 WARN (broth :: itch-setup:windows-amd64-head) While checking for latest version: Error: net::ERR_INTERNET_DISCONNECTED
    at ClientRequest.req.on.error (C:\msys64\home\amos\Dev\itch\dist\main\main.bundle.js:12765:20)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at URLRequest._emitRequestEvent (C:\msys64\home\amos\Dev\itch\node_modules\electron\dist\resources\electron.asar\browser\api\net.js:90:24)
07:27:44.820 ERROR while reacting to checkForComponentUpdates: Error: Could not retrieve latest version of (itch-setup): net::ERR_INTERNET_DISCONNECTED
    at package_Package.doUpgrade (C:\msys64\home\amos\Dev\itch\dist\main\main.bundle.js:22053:19)
    at <anonymous>
EventSource error: Error: net::ERR_NETWORK_CHANGED
Caught butler error:
JavaScript stack: Error: net::ERR_NETWORK_CHANGED
07:27:50.682 ERROR while reacting to checkForGameUpdates: Error: net::ERR_NETWORK_CHANGED
Caught butler error:
JavaScript stack: Error: net::ERR_CONNECTION_REFUSED
07:35:17.087 WARN (m/reac/commons) While fetching commons: Error: net::ERR_CONNECTION_REFUSED
07:53:35.383 INFO (m/reac/updater) Regularly scheduled check for game updates...
07:53:35.398 INFO (m/reac/updater) Scheduling next game update check for Sat Aug 04 2018 10:19:13 GMT+0200 (Romance Daylight Time)
EventSource error: Error: net::ERR_CONNECTION_REFUSED
Caught butler error:
JavaScript stack: Error: net::ERR_CONNECTION_REFUSED
```

### PR DESCRIPTION
**Pull request by exelotl**
Amos had to hold my hand a lot but I got there eventually!

To break it down:
- butlerd lifecycle was dependent on an ongoing connection to the 'flow' endpoint, which would usually be terminated by the itch app when we wanted to restart butler (due to an update)
- However, the connection could also be killed when Windows goes to sleep, in which case butlerd would terminate gracefully but no new instance would be created to take its place
- To fix this, we no longer use the flow endpoint, but instead call the shutdown endpoint to explicitly request a graceful shutdown of butlerd

### CODE REVIEW

File: src/main/reactors/setup.ts [hunk 1]
```diff
@@ -222,31 +206,8 @@ async function refreshButlerd(store: Store) {
...
-          logger.info(
-            `butlerd instance ${
-              inc.id
-            } exited! (${elapsed.toFixed()} ms after shutdown request)`
-          );
-          clearInterval(interval);
-        }
-      }, intervalMs);
-    }
+    let client = new Client(await previousIncarnation.instance.getEndpoint());
```
Comment (fasterthanlime) [inline src/main/reactors/setup.ts]: I guess here I would
  * Store the client in `previousIncarnation`
  * Remove the convo field from `previousIncarnation`'s type, because we're not using it anymore!

**Comment by fasterthanlime** [comment]
Thanks! I left one review comment.

**Review by fasterthanlime — CHANGES_REQUESTED** [review]

**Comment by exelotl** [comment]
How's this? :>
